### ISSUE TITLE
Amazon Linux 2 has 'awslogsd' as service name

### ISSUE THREAD

**Issue by jyaworski** [dharrisio/ansible-role-aws-cloudwatch-logs-agent#22]
On Amazon Linux 2, `awslogsd` is the service name, while this is hardcoded to `awslogs`. Can we have a variable to set the service name?

**Comment by anttu** [comment]
Backported fix: https://github.com/anttu/ansible-role-aws-cloudwatch-logs-agent/tree/0.1.1-parameterize-daemon-name
