### ISSUE TITLE
Publish v0.1.1 to Galaxy?

### ISSUE THREAD

**Issue by tomyam1** [dharrisio/ansible-role-aws-cloudwatch-logs-agent#9]
Can you please publish the latest code to galaxy?

**Comment by dharrisio** [comment]
v0.1.1 has been published in Galaxy.

**Comment by tomyam1** [comment]
Thanks!

טום ים | Tepez | מנכ"ל
tomyam@tepez.co.il | M: +972 52 3200411 | Skype: tom.yam1
LinkedIn: tomyam <https://www.linkedin.com/in/tomyam> | Github: tomyam1
<https://github.com/tomyam1>
www.tepez.co.il
